/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interfaces;

import Principal.Transacao;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Tiago
 */
public class cadTranCompra extends javax.swing.JFrame {

    /**
     * Creates new form cadTranCompra
     */
    public cadTranCompra() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        cx1 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        cx2 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jButton7 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        cx3 = new javax.swing.JTextField();
        cx4 = new javax.swing.JTextField();
        cx5 = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Cadastro de Transação - Compra");
        setResizable(false);

        jLabel1.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jLabel1.setText("Fornecedor: ");

        jLabel2.setFont(new java.awt.Font("Verdana", 0, 24)); // NOI18N
        jLabel2.setText("Transação: Compra");

        jLabel3.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jLabel3.setText("Produto: ");

        jLabel4.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jLabel4.setText("Preço Unitario: ");

        jLabel5.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jLabel5.setText("Quantidade: ");

        jLabel6.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jLabel6.setText("Desconto (%): ");

        jLabel7.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jLabel7.setText("Total: ");

        jButton7.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jButton7.setText("CANCELAR");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        jButton9.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jButton9.setText("FINALIZAR");
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jLabel8.setText("ID:");

        jLabel9.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jLabel9.setText(Integer.toString(incrId()));

        jLabel10.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jLabel10.setText("VALOR");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(0, 25, Short.MAX_VALUE)
                                .addComponent(cx2, javax.swing.GroupLayout.PREFERRED_SIZE, 298, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(cx1)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButton7)
                        .addGap(18, 18, 18)
                        .addComponent(jButton9))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cx3, javax.swing.GroupLayout.PREFERRED_SIZE, 298, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cx4, javax.swing.GroupLayout.PREFERRED_SIZE, 298, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cx5, javax.swing.GroupLayout.PREFERRED_SIZE, 298, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(27, 27, 27))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(98, 98, 98)
                        .addComponent(jLabel2))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel9)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(4, 4, 4)
                .addComponent(jLabel2)
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jLabel9))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(cx1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(cx2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(cx3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(cx4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(cx5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(9, 9, 9)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jLabel10))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 39, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton7)
                    .addComponent(jButton9))
                .addGap(29, 29, 29))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        dispose();
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        MyConnection mc = new MyConnection();
        Connection cn = mc.conexao();
        Transacao tran = new Transacao();
        boolean cond = false;
        int c = 0;
        String sql;
        String sql2;
        String sql3;
        try {
            if (cx1.getText().equals("") || cx2.getText().equals("") || cx3.getText().equals("") || cx4.getText().equals("") || cx5.getText().equals("")) {
                throw new Exception();
            } else {
                tran.getPes().setNome(cx1.getText());
                tran.getProd().setNome(cx2.getText());
                tran.setValor_un(Float.parseFloat(cx3.getText()));
                tran.setQtde(Integer.parseInt(cx4.getText()));
                tran.setDesconto(Integer.parseInt(cx5.getText()));
                tran.setValorTotal(calcTotal());
                c = 1;
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Todos os campos devem ser preenchidos", "Transação de Compra", JOptionPane.ERROR_MESSAGE);
            c = 2;
        }
        if (c == 1) {
            sql = "INSERT INTO Transacao (Tipo, Quantidade, Valor_unitario, Valor_tot, Desconto, ID_Pes, ID_Prod) VALUES ('C', ?, ?, ?, ?, ?, ?);";
            sql2 = "INSERT INTO Estoque (quantidade, ID_Prod) VALUES (?, ?);";
            sql3 = "UPDATE Estoque SET quantidade = quantidade + ? WHERE ID_Prod = ?";

            while (cond != true) {
                try {
                    PreparedStatement psd = cn.prepareStatement(sql);
                    psd.setInt(1, tran.getQtde());
                    psd.setFloat(2, tran.getValor_un());
                    psd.setFloat(3, tran.getValorTotal());
                    psd.setInt(4, tran.getDesconto());
                    psd.setInt(5, getIdPes(tran));
                    psd.setInt(6, getIdPro(tran));

                    int n = psd.executeUpdate();
                    if (n > 0) {

                        try {
                            PreparedStatement psd2 = cn.prepareStatement(sql2);
                            psd2.setInt(1, tran.getQtde());
                            psd2.setInt(2, getIdPro(tran));

                            int n2 = psd2.executeUpdate();

                            if (n2 > 0) {
                                JOptionPane.showMessageDialog(null, "Transacao salva", "Transação de Compra", JOptionPane.INFORMATION_MESSAGE);
                                int op = JOptionPane.showConfirmDialog(null, "Deseja realizar outra transação agora?", "Transação de Compra", JOptionPane.YES_NO_OPTION);
                                if (op == 0) {
                                    cond = true;
                                    dispose();
                                    new cadTranCompra().setVisible(true);

                                } else {
                                    dispose();
                                    cond = true;
                                }
                            }
                        } catch (SQLException ex) {
                            Logger.getLogger(cadProd.class.getName()).log(Level.SEVERE, null, ex);
                            
                            PreparedStatement psd3 = cn.prepareStatement(sql3);
                            psd3.setInt(1, tran.getQtde());
                            psd3.setInt(2, getIdPro(tran));

                            int n2 = psd3.executeUpdate();

                            if (n2 > 0) {
                                JOptionPane.showMessageDialog(null, "Transacao salva", "Transação de Compra", JOptionPane.INFORMATION_MESSAGE);
                                int op = JOptionPane.showConfirmDialog(null, "Deseja realizar outra transação agora?", "Transação de Compra", JOptionPane.YES_NO_OPTION);
                                if (op == 0) {
                                    cond = true;
                                    dispose();
                                    new cadTranCompra().setVisible(true);

                                } else {
                                    dispose();
                                    cond = true;
                                }
                            }
                        }

                    }

                } catch (SQLException ex) {
                    Logger.getLogger(cadProd.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        }
    }//GEN-LAST:event_jButton9ActionPerformed

    public float calcTotal() {

        float quant = Float.parseFloat(cx3.getText());
        float valor = Float.parseFloat(cx4.getText());
        float des = Float.parseFloat(cx5.getText());
        float total = ((valor * quant) * (100 - des)) / 100;

        return total;
    }

    public static int incrId() {
        int id = 0;
        try {
            MyConnection mc = new MyConnection();
            Connection cn = mc.conexao();
            PreparedStatement psd = cn.prepareStatement("SELECT * FROM Transacao");
            ResultSet rs = psd.executeQuery();
            while (rs.next()) {
                id = (rs.getInt("ID_Trans"));
            }
        } catch (SQLException ex) {
            Logger.getLogger(cadProd.class.getName()).log(Level.SEVERE, null, ex);
        }
        if (id == 0) {
            return 1;
        } else {
            return (id + 1);
        }
    }

    public int getIdPes(Transacao tran) {
        int id = 0;
        try {
            MyConnection mc = new MyConnection();
            Connection cn = mc.conexao();
            PreparedStatement psd = cn.prepareStatement("SELECT ID_Pes FROM Pessoa WHERE Nome = ?;");
            psd.setString(1, tran.getPes().getNome());

            ResultSet rs = psd.executeQuery();
            while (rs.next()) {
                id = (rs.getInt("ID_Pes"));
            }
        } catch (SQLException ex) {
            Logger.getLogger(cadProd.class.getName()).log(Level.SEVERE, null, ex);
        }
        return id;
    }

    public int getIdPro(Transacao tran) {
        int id = 0;
        try {
            MyConnection mc = new MyConnection();
            Connection cn = mc.conexao();
            PreparedStatement psd = cn.prepareStatement("SELECT ID_Prod FROM Produto WHERE Nome = ?;");
            psd.setString(1, tran.getProd().getNome());

            ResultSet rs = psd.executeQuery();
            while (rs.next()) {
                id = (rs.getInt("ID_Prod"));
            }
        } catch (SQLException ex) {
            Logger.getLogger(cadProd.class.getName()).log(Level.SEVERE, null, ex);
        }
        return id;
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(cadTranCompra.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(cadTranCompra.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(cadTranCompra.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(cadTranCompra.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new cadTranCompra().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField cx1;
    private javax.swing.JTextField cx2;
    private javax.swing.JTextField cx3;
    private javax.swing.JTextField cx4;
    private javax.swing.JTextField cx5;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    // End of variables declaration//GEN-END:variables
}
